pipeline:
  name: korede
  identifier: korede
  projectIdentifier: test # Replace with the correct project identifier (e.g., 'Terragrunt-project')
  orgIdentifier: default
  tags: {}

  stages:
    - stage:
        name: Terragrunt Deployment
        identifier: terragrunt_deployment
        type: Deployment
        spec:
          execution:
            steps:
              - step:
                  name: Terragrunt Init
                  identifier: terragrunt_init
                  type: Run
                  spec:
                    connectorRef: <your-vcs-connector>  # Replace with the correct connector reference (e.g., 'github-connector')
                    command: |
                      terragrunt init
                    workingDirectory: "/terragrunt-ecs-nginx/non-prod/us-east-1"

              - step:
                  name: Terragrunt Plan
                  identifier: terragrunt_plan
                  type: Run
                  spec:
                    connectorRef: <your-vcs-connector>  # Replace with the correct connector reference
                    command: |
                      terragrunt plan
                    workingDirectory: "/terragrunt-ecs-nginx/non-prod/us-east-1"

              - step:
                  name: Terragrunt Apply
                  identifier: terragrunt_apply
                  type: Run
                  spec:
                    connectorRef: <your-vcs-connector>  # Replace with the correct connector reference
                    command: |
                      terragrunt apply --auto-approve
                    workingDirectory: "/terragrunt-ecs-nginx/non-prod/us-east-1"
